# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postulacion',
            options={'verbose_name': 'Postulación', 'verbose_name_plural': 'Postulaciones'},
        ),
    ]
