# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('parte_a', models.CharField(max_length=5)),
                ('parte_b', models.CharField(max_length=5)),
                ('parte_final', models.CharField(max_length=5)),
                ('nota', models.CharField(max_length=5)),
                ('situacion', models.CharField(max_length=20)),
                ('periodo', models.CharField(max_length=4)),
                ('rutx', models.CharField(max_length=10)),
            ],
        ),
    ]
