# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensura', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensurageneral',
            old_name='rut_perito',
            new_name='usuario_id',
        ),
    ]
