# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='archivo_ant',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='archivo_ci',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='archivo_titulo',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
