# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20170621_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, default='user', max_length=5),
        ),
    ]
