# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-10 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renovacion',
            name='doc_ant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='renovacion',
            name='doc_ci',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='renovacion',
            name='doc_tit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
