# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renovacion', '0003_renovacion_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renovacion',
            options={'verbose_name': 'Renovación', 'verbose_name_plural': 'Renovaciones'},
        ),
    ]
