# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apelacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apelacion',
            options={'verbose_name': 'Apelación', 'verbose_name_plural': 'Apelaciones'},
        ),
    ]
