# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apelacion', '0003_auto_20180523_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='apelacion',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
