# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-13 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_nomina', models.CharField(max_length=11)),
                ('nombre_nomina', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=4)),
            ],
        ),
    ]
