# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='ord_region',
            field=models.IntegerField(null=True),
        ),
    ]
