# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 00:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=80)),
                ('region', models.CharField(max_length=30)),
                ('comuna', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'SOLTERO(A)'), ('CASADO', 'CASADO(A)'), ('VIUDO', 'VIUDO(A)')], max_length=20)),
                ('telefono_casa', models.IntegerField()),
                ('telefono_cel', models.IntegerField()),
                ('profesion', models.CharField(max_length=40)),
                ('universidad', models.CharField(max_length=50)),
                ('archivo_titulo', models.CharField(blank=True, max_length=300)),
                ('archivo_ci', models.CharField(blank=True, max_length=300)),
                ('archivo_ant', models.CharField(blank=True, max_length=300)),
                ('year_titulo', models.IntegerField()),
                ('empresa', models.CharField(max_length=50)),
                ('telefono_empresa', models.IntegerField()),
                ('direccion_empresa', models.CharField(max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
