# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-21 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telefono_casa',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono_cel',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono_empresa',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
