# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='provincia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
