# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20180321_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comuna',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='estado_civil',
            field=models.CharField(choices=[('-1', 'Seleccione'), ('SOLTERO', 'SOLTERO(A)'), ('CASADO', 'CASADO(A)'), ('VIUDO', 'VIUDO(A)'), ('DIVORCIADO', 'DIVORCIADO(A)')], default='Seleccione', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genero',
            field=models.CharField(choices=[('S', 'Seleccione'), ('M', 'MASCULINO'), ('F', 'FEMENINO')], default='S', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profesion',
            field=models.CharField(choices=[('-1', 'Seleccione'), ('ingGeoMen', 'Ingeniero en Geomensura'), ('ingEjecGeo', 'Ingeniero de Ejecución en Geomensura'), ('ingEjecMin', 'Ingeniero de Ejecución en Minas')], default='Seleccione', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='provincia',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
