# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20170817_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fecha_nac',
            field=models.DateField(),
        ),
    ]
