# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20180504_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='archivo_ant',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='archivo_ci',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='archivo_titulo',
        ),
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
