# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20170817_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fecha_nac',
        ),
    ]
