# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20180511_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='renovante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='sngm',
            field=models.BooleanField(default=False),
        ),
    ]
