# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_remove_profile_fecha_nac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='apellido_m',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='apellido_p',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='archivo_ant',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='archivo_ci',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='archivo_titulo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='direccion_empresa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profesion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telefono_casa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telefono_empresa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='universidad',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year_titulo',
        ),
        migrations.AlterField(
            model_name='profile',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
    ]
