# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-15 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20180302_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='archivo_ant',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='archivo_ci',
            field=models.FileField(blank=True, null=True, upload_to='Archivo/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='archivo_titulo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
