# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20170817_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='direccion',
            field=models.CharField(default='CALLE BIEN Y TU', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono_cel',
            field=models.IntegerField(default=123),
        ),
    ]
