# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20170817_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apellido_m',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='apellido_p',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='archivo_ant',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='archivo_ci',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='archivo_titulo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='comuna',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='direccion_empresa',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='empresa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTERO', 'SOLTERO(A)'), ('CASADO', 'CASADO(A)'), ('VIUDO', 'VIUDO(A)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='genero',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nacionalidad',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombres',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profesion',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono_casa',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono_empresa',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='universidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='year_titulo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='direccion',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono_cel',
            field=models.IntegerField(null=True),
        ),
    ]
