# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20170817_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rut',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
