# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-05 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoproceso',
            name='periodo',
            field=models.CharField(max_length=9),
        ),
    ]
